name: Prepare Deployment Repository
description: Update yaml files with new values using yq
inputs:
  k8s_target_full_paths:
    description: Target Path/File within the k8s repo to parse and commit tag updates
    required: true
  k8s_yq_paths:
    description: Comma-separated string list of yq yaml paths to update
    required: true
  update_value:
    description: Full value that should be updated in place for ArgoCD gitops
    required: true

runs:
  using: composite
  steps:
    - name: Update YAML files
      shell: bash
      run: |
        set -x
        read -ra target_paths <<< "${{ inputs.k8s_target_full_paths }}"
        for target_path in ${target_paths[@]}
          do
            if [ ! -f "${target_path//,}" ]; then echo "${target_path//,} not found; exit code 1" && exit 1; fi
            read -ra update_paths <<< "${{ inputs.k8s_yq_paths }}"
            for update_path in ${update_paths[@]}
              do
                yq --inplace "${update_path} = \"${{inputs.update_value}}\"" "${target_path}"
              done
          done
        git diff