name: Test Extract Package Info Action

on:
  push:
    branches: [main]
    paths:
      - 'extract-package-info/**'
  pull_request:
    branches: [main]
    paths:
      - 'extract-package-info/**'
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/reusable-test-bats.yml
    with:
      action-folder: 'extract-package-info'